#
# SPDX-License-Identifier:	GPL-2.0+
#

head-y := arch/mips/cpu/start.o

libs-y += arch/mips/cpu/
libs-y += arch/mips/lib/

libs-$(CONFIG_SOC_AU1X00) += arch/mips/mach-au1x00/
libs-$(CONFIG_SOC_QCA955X) += arch/mips/mach-qca955x/