#
# (C) Copyright 2003-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= board955x.o
obj-y	+= common/tap-955x.o
obj-y	+= common/init-955x.o
obj-y	+= common/955x.o

