#
# (C) Copyright 2011
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# obj-y	 = start.o
# obj-y	+= cpu.o
extra-y += 
obj-y	+= init-955x.o

# extra-y += tap-955x.o 955x.o
# obj-y	+= 955x.o cache.o 