#
# (C) Copyright 2011
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# obj-y	 = start.o
# obj-y	+= cpu.o
obj-y	+= cache.o 955x.o init-955x.o tap-955x
