#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_ATHRS_GMAC_955X) +=  qca-eth-955x.o
obj-$(CONFIG_ATHRS_GMAC_953X) +=  qca-eth-953x.o
obj-$(CONFIG_ATHRS17_PHY) += athrs17_phy.o rgmii-cal-955x.o athrs17_lpbk.o
obj-$(CONFIG_PHY_AR803X) += athr_ar8033_phy.o
